# Generated by Django 4.2.4 on 2023-08-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='mombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='apelldio',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='mombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='apelldio',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
